yarnPath: .yarn/releases/yarn-4.1.1.cjs
nodeLinker: node-modules
nmMode: hardlinks-local

npmScopes:
  mykin-ai:
    npmPublishRegistry: ${NPM_PUBLISH_REGISTRY:-https://npm.pkg.github.com}
    npmAuthToken: ${NODE_AUTH_TOKEN:-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}
